import turtle


print("\n\n .................your program is start............... \n")
ans = input(".....hey Hi *'I love you'* .Do you Love Me ?, \n >>>>>    say 'yes' otherwise say 'no'\n ............>> ")

if ans == "yes":
    print("wao")
    screen = turtle.Screen()
    turtle.title("Love Message")
    screen.setup(width = 1.0, height = 1.0)
    t = turtle.Turtle()
    t.color("white")
    turtle.bgcolor("black")
    #t.goto(-100,0)
    t.left(50)
    t.forward(150)
    t.speed(20)
    t.begin_fill()
    for i in range(100):
        t.left(2)
        t.forward(2)
    t.right(140)
    for i in range(100):
        t.left(2)
        t.forward(2)
    t.forward(152)
    t.fillcolor("red")
    t.end_fill()
    t.penup()
    t.goto(-150,0)
    t.left(90)
    t.pen(pensize=3,speed=5)
    t.pendown()
    t.shapesize(3,3,3)
    t.forward(400)
    t.stamp()

    t.penup()
    t.home()
    t.goto(-500,-300)
    t.pen(pencolor="white",pendown=True,pensize=3)
    t.forward(50)
    t.backward(25)
    t.left(90)
    t.forward(100)
    t.left(90)
    t.forward(25)
    t.backward(50)


    t.right(180)
    t.penup()
    t.forward(200)
    t.pendown()
    t.right(90)
    t.forward(100)
    t.left(90)
    t.forward(50)
    t.penup()
    t.forward(50)
    t.pendown()
    t.circle(50)
    t.penup()
    t.forward(60)
    t.left(90)
    t.forward(100)
    t.pendown()
    t.right(150)
    t.forward(120)
    t.left(120)
    t.forward(120)
    t.penup()
    t.right(60)
    t.forward(70)
    t.pendown()
    t.backward(50)
    t.right(90)
    t.forward(50)
    t.left(90)
    t.forward(40)
    t.backward(40)
    t.right(90)
    t.forward(50)
    t.left(90)
    t.forward(50)


    t.penup()
    t.forward(200)
    t.left(90)
    t.forward(100)
    t.pendown()
    t.right(180)
    t.forward(70)
    for i in range(90):
        t.left(2)
        t.forward(2)
    t.forward(70)
    turtle.done()

elif ans == "no":
    print("Oh NO")
    
else:
    print("You Enter Wrong Key ")